# ============================================
# Instancia: NOMBRE_CLIENTE
# Dominio: NOMBRE_CLIENTE.openvoo.com
# ============================================

networks:
  openvoo_network:
    external: true

volumes:
  NOMBRE_CLIENTE_data:
  NOMBRE_CLIENTE_web:

services:
  NOMBRE_CLIENTE:
    image: odoo:19.0
    container_name: NOMBRE_CLIENTE
    restart: unless-stopped
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ../../enterprise:/mnt/enterprise:ro
      - ./addons:/mnt/custom-addons
      - NOMBRE_CLIENTE_data:/var/lib/odoo
      - NOMBRE_CLIENTE_web:/var/lib/odoo/filestore
    networks:
      - openvoo_network
