# ============================================
# Instancia: Demo
# Dominio: demo.openvoo.com
# ============================================

networks:
  openvoo_network:
    external: true

volumes:
  demo_data:
  demo_web:

services:
  demo:
    image: odoo:19.0
    container_name: demo
    restart: unless-stopped
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ../../enterprise:/mnt/enterprise:ro
      - ./addons:/mnt/custom-addons
      - demo_data:/var/lib/odoo
      - demo_web:/var/lib/odoo/filestore
    networks:
      - openvoo_network
